# Generated by Django 5.1.6 on 2025-02-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('institution_name', models.CharField(max_length=255)),
                ('institution_city', models.CharField(max_length=100)),
                ('institution_state', models.CharField(max_length=100)),
                ('institution_country', models.CharField(max_length=100)),
                ('institution_address', models.CharField(max_length=255)),
                ('institution_postal_code', models.CharField(max_length=20)),
            ],
        ),
    ]
