# Generated by Django 4.0.6 on 2024-07-27 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AIPL', '0002_datadeletionmodel_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datadeletionmodel',
            options={'verbose_name': 'Data Deletion Request', 'verbose_name_plural': 'Data Deletion Requests'},
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('reason', models.CharField(choices=[('Consultation', 'Consultation'), ('Support', 'Support'), ('Demo', 'Demo'), ('Product Demonstration', 'Product Demonstration'), ('Business Development', 'Business Development'), ('Strategic Planning', 'Strategic Planning'), ('Project Kickoff', 'Project Kickoff'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['date', 'time'],
            },
        ),
    ]
