# Generated by Django 4.0.6 on 2024-09-30 18:19

import AIPL.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIPL', '0002_team_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('institute_name', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer'), ('manager', 'Manager'), ('frontend_dev', 'Frontend Dev'), ('backend_dev', 'Backend Dev'), ('devops_eng', 'DevOps Eng'), ('fullstack_dev', 'Fullstack Dev'), ('aa_dev', 'AA Dev'), ('ios_dev', 'IOS Dev'), ('software_dev', 'Software Dev'), ('ai_ml_eng', 'AI/ML Eng'), ('data_analyst', 'Data Analyst'), ('db_admin', 'DB Admin'), ('cloud_dev', 'Cloud Dev'), ('blockchain_dev', 'Blockchain Dev'), ('ar_vr_dev', 'AR/VR Dev'), ('test_automation', 'Test Automation')], max_length=100)),
                ('branch', models.CharField(choices=[('cse', 'Computer Science'), ('ee', 'Electrical Engineering'), ('me', 'Mechanical Engineering'), ('ce', 'Civil Engineering'), ('it', 'Information Technology'), ('ae', 'Aeronautical Engineering'), ('bioe', 'Biotechnology Engineering'), ('ece', 'Electronics and Communication Engineering'), ('chem', 'Chemical Engineering'), ('data', 'Data Science'), ('mse', 'Materials Science and Engineering'), ('env', 'Environmental Engineering'), ('automobile', 'Automobile Engineering')], max_length=100)),
                ('linkedin_profile_url', models.URLField(blank=True, null=True)),
                ('github_profile_url', models.URLField(blank=True, null=True)),
                ('custom_resume', models.FileField(blank=True, null=True, upload_to='nginx/resumes/', validators=[AIPL.models.validate_file_size, AIPL.models.validate_file_extension])),
                ('college_id', models.CharField(max_length=100)),
            ],
        ),
    ]
