# Generated by Django 5.1.2 on 2024-12-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIPL', '0002_internshipapplication_date_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managetask',
            name='task_progress',
            field=models.CharField(choices=[('not started', 'Not Started'), ('in progress', 'In Progress'), ('completed', 'Completed'), ('dismantel', 'Dismantel')], default='not started', max_length=20),
        ),
    ]
