# Generated by Django 5.1.2 on 2024-11-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIPL', '0002_alter_developer_profile_job_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managetask',
            name='task_detail',
            field=models.TextField(max_length=2000),
        ),
    ]
