# Generated by Django 4.0.6 on 2024-09-12 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AIPL', '0007_developer_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer_profile',
            options={'verbose_name': "AIPL's Employee 🧑\u200d🔬", 'verbose_name_plural': "AIPL's Employee 🧑\u200d🔬"},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Available Meeting', 'verbose_name_plural': 'Available Meeting'},
        ),
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'verbose_name': 'Email Sender (Limited to Subscribers) 📧', 'verbose_name_plural': 'Email Sender (Limited to Subscribers) 📧'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notify/Update Sender 📧', 'verbose_name_plural': 'Notify/Update Sender 📧'},
        ),
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': "View Subscriber's Email 👤", 'verbose_name_plural': "View Subscriber's Email 👤"},
        ),
        migrations.AlterField(
            model_name='developer_profile',
            name='developer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee ID'),
        ),
        migrations.CreateModel(
            name='AddTaskDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('detail', models.TextField(max_length=800)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Assign Tool 🧑\u200d🔬',
                'verbose_name_plural': 'Task Assign Tool 🧑\u200d🔬',
            },
        ),
    ]
